### ISSUE TITLE
ルートフォルダのmanifest.jsonのバージョン管理について

### ISSUE THREAD

**Issue by rinjugatla** [alpaca-honke/twishare-to-misskey#24]
開発のテストとして以下の手順を踏んでいます。
1. manifest.jsonをルートフォルダに配置
2. 拡張機能の追加でルートフォルダを読み込み
3. コードを編集
4. テスト
5. 変更をコミット

手順5のコミットの際に手順1で配置したしたルートのmanifest.jsonがバージョン管理に表示されます。
間違えて追加しそうなのでバージョン管理の除外に定義するのはどうでしょうか？
リリース作業などで除外できない事情などあれば教えてください。

**Comment by alpaca-honke** [comment]
Chrome版とFirefox版を同じブランチで管理するようにしたのが現時点最新リリース（v0.2.4）で、その前はdevelopとmainブランチにはChrome版のソースコードしか置いてなかったので、その名残です…

出来れば今日中に僕が.gitignore追加しておきます。

提案ありがとうございます！

**Comment by alpaca-honke** [comment]
コミットメッセージにclose書き忘れた
