### ISSUE TITLE
シェア先のインスタンスのドメインの保存に失敗したのに「保存しました！」と表示される

### ISSUE THREAD

**Issue by alpaca-honke** [alpaca-honke/twishare-to-misskey#3]
# 概要

Firefoxで、storage.syncの使用が許可されていない状態で実行しようとした際、正常に保存できていないにもかかわらず、ポップアップに「保存しました！」と表示される。

# バグの再現

storage.syncが許可されていない状態（拡張機能IDが設定されていないなど）で保存を行おうとすると、保存されていないのに保存されたかのように見える。

# 期待する挙動

正常に保存されたときは「保存しました！」と表示され、それ以外の場合は何も表示されないか、「保存できませんでした」と表示される。

**Comment by alpaca-honke** [comment]
関係するところとして、フォーム内でEnterして保存したときは「保存しました！」が表示されるが、保存ボタンを押して保存したときは表示されない、という問題もある。（Issue開くのめんどくさいし修正点ほぼ同じだからこのIssueに含まれるものとする）

**Comment by alpaca-honke** [comment]
いまからやる

**Comment by alpaca-honke** [comment]
v0.1.1でリリース予定

**Comment by massongit** [comment]
https://github.com/alpaca-honke/twishare-to-misskey/blob/f6a2b5636d6ad425f51f62213e85150e043c7bb6/options.js#L30-L34

https://github.com/alpaca-honke/twishare-to-misskey/commit/a50d947a12d942e2c2af01ff63ed3079eeac8da3 で追加された上記関数が使われていないようですが、実装が漏れていたりはしないでしょうか？
