### ISSUE TITLE
Firefoxで設定が保存されない

### ISSUE THREAD

**Issue by tonby** [alpaca-honke/twishare-to-misskey#58]
Firefoxのアドオン設定画面でサーバー名などの値を入力しても反映されず、開き直すと初期値に戻っています。
「更新内容/お知らせはこちら」もリンクが機能していないため、アドオン設定画面自体が正しく機能していない気がします。
前は正しく動いていたと記憶しているので環境の問題かもしれませんが、念の為ご報告させて頂きます。

Firefox: 128.0.3 (64 ビット)
Twishare to misskey: v0.3.2

**Comment by alpaca-honke** [comment]
ご報告ありがとうございます！
2点ほどお聞きしたいことがあります。
① 覚えてればで大丈夫ですが、最後に正常に動作したFirefoxのバージョンは覚えていますでしょうか？
② 現在不具合が発生しているOSを教えていただけますか？

当方でもできる限り早く確認と修正したいと考えていますが、多忙によりすぐに修正、とは行かない可能性が高いです。
よろしくお願いします。

**Comment by tonby** [comment]
現在のOSはwin11です。
OSを新しいSSDにクリーンインストールしたので、以前とは大きく環境が変わっています。
古いSSDのOS(win10)を起動してみたところ、
Firefox: 125.0.3
Twishare: v0.3.0
のようでしたが、自動更新されてしまったため正確な情報が確認できていません。
ただ、Twishareが更新されたタイミングでやはり設定画面が動かなくなったので、OSやFirefoxのバージョンは関係ないのかもしれません。

**Comment by alpaca-honke** [comment]
なるほど、ありがとうございます
Twishareが0.3.2に更新された時点で不具合が発生した可能性があるとの認識ですかね？
こちらでもできる限り早く確認・修正させていただきます！

**Comment by alpaca-honke** [comment]
メモ:
- 多分関係ないとは思うが保存情報の保存先をsyncからlocalに変えてみる
- それでも上手くいかなければどっかでエラーが出てる可能性が高いから探す

挙動に関して:
- Chrome系 (Google Chrome, MIcrosoft Edge で確認) では全て正常に動作していることを確認
- Firefox系 (Firefox, Firefox for Android, Waterfox で確認した) は全滅

**Comment by alpaca-honke** [comment]
@tonby もうひとつ、覚えていればお聞きしたいことがあります
最後に正常に動作していた（前のSSDで動作していた？）時期を教えていただきたいです！
昔は動いていたからどこかのバージョンから動かなくなったんじゃないかと思ってるのでそのバージョンを調べたくて…。
教えて頂けたら嬉しいです！

**Comment by alpaca-honke** [comment]
ストアで公開してるやつは動かないのにローカルで動かしたら動く
まじで謎

**Comment by tonby** [comment]
返信遅くなり申し訳ございません。
設定はめったに変更しないので正確には分かりませんが、3ヶ月前の5/18に共有ボタンの表示/非表示を切り替えたっぽくて、その時に何も気付かなかったと思うので、その時点では正しく動いていたのではないかと思います。

**Comment by alpaca-honke** [comment]
@tonby ありがとうございます！なんとなく前回の更新からの不具合な気がする…
とりあえず動くものは出来てリリースしたいので今週中には、って思っているところです
こちらこそ対応がすぐに出来なくて申し訳ないです、もう少しお待ちください！

**Comment by alpaca-honke** [comment]
@tonby 
修正したものをリリースしました！ご確認ください！

**Comment by tonby** [comment]
ありがとうございます！無事動くようになりました！
